# Generated by Django 5.1.1 on 2024-09-20 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_alter_story_description_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='story.story'),
        ),
    ]
