# Generated by Django 5.1.1 on 2024-09-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_story_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='categories',
            field=models.ManyToManyField(to='story.category'),
        ),
    ]
